# Information
site_name: ORIGIN EFFECT
site_url: https://zh.origineffect.net
site_description: Origin Effect Docs

# Configuration
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes

# Additional
extra:
  alternate:
    - name: 简体中文
      link: zh.origineffect.net
      lang: zh
    - name: English
      link: origineffect.net
      lang: en

# Navigation
nav:
  - Home: index.md
  - CUBE CORE: cube-core/index.md