# Information
site_name: ORIGIN EFFECT
site_url: https://zh.origineffect.net
site_description: Origin Effect Docs

# Configuration
theme:
  name: material
  language: en
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: octicons/moon-16
        name: Switch to system preference
  features:
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes

# Hooks
hooks:
  - overrides/hooks/i18n-stayonpage.py

# Additional
extra:
  alternate:
    - name: English
      link: https://origineffect.net
      lang: en
    - name: 简体中文
      link: https://zh.origineffect.net
      lang: zh

# Navigation
nav:
  - Home: index.md
  - CUBE CORE: cube-core/index.md