name: Deploy Docs

on:
  workflow_run:
    workflows:
      - Build Docs
    types:
      - completed

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Download Artifact Docs
        id: download
        uses: actions/download-artifact@v4
        with:
          path: site
      - name: Display structure of downloaded files
        run: ls
      - name: Deploy
        run: |
          pip install typer
          pip install mkdocs-material
          python ./build/build-docs.py
          mkdocs gh-deploy --force
